/** HamroBazar bug report — organized by module (from Playwright QA + manual checks) */
module.exports = [
  {
    id: 'BUG-HB-001',
    module: 'Chat',
    feature: 'Start a chat',
    title: 'Chat feature shows "Under construction" instead of opening chat',
    severity: 'Major',
    priority: 'P0',
    status: 'Open',
    type: 'Functional',
    testCaseIds: '—',
    steps:
      '1. Open https://hamrobazaar.com\n2. Open any ad detail page\n3. Click "Start a chat"\n4. Observe dialog content',
    expected: 'Chat opens or prompts user to sign in and start messaging the seller.',
    actual:
      'Modal appears with message "Under construction" and "We are working on the chat feature." User must click "Got it" to dismiss.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium)',
    evidence: 'tests/09-chat.spec.js; playwright-report',
    reportedBy: 'Playwright QA',
    date: '2026-06-16',
    comments: 'Automated tests pass because they assert the placeholder dialog. Feature is not live for buyers/sellers.',
  },
  {
    id: 'BUG-HB-002',
    module: 'Chat',
    feature: 'Chat page',
    title: 'Dedicated /chat page does not provide messaging for guests',
    severity: 'Minor',
    priority: 'P2',
    status: 'Open',
    type: 'Functional',
    testCaseIds: '—',
    steps:
      '1. Open https://hamrobazaar.com/chat (not signed in)\n2. Review page content',
    expected: 'Guest sees chat inbox or clear path to sign in and use chat.',
    actual: 'Page loads but only shows Sign in option; underlying chat feature is under construction.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium)',
    evidence: 'tests/09-chat.spec.js',
    reportedBy: 'Playwright QA',
    date: '2026-06-16',
    comments: 'Related to BUG-HB-001. Consider hiding chat entry points until feature ships.',
  },
  {
    id: 'BUG-HB-003',
    module: 'Auth',
    feature: 'Phone validation',
    title: 'Login phone field shows invalid state for valid 10-digit Nepal mobile number',
    severity: 'Major',
    priority: 'P0',
    status: 'Open',
    type: 'Validation',
    testCaseIds: 'C15, C19',
    steps:
      '1. Go to https://hamrobazaar.com/login\n2. Enter phone: 9877692345\n3. Enter any password\n4. Tab out of phone field or click Log In',
    expected: 'Valid 10-digit Nepal mobile (98xxxxxxxx) is accepted without error styling.',
    actual:
      'Phone input displays red error border / invalid state even though the number matches expected Nepal mobile format.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium)',
    evidence: 'phone-validation.png',
    images: ['phone-validation.png'],
    reportedBy: 'Manual QA',
    date: '2026-06-16',
    comments: 'User reported "invalid number" UI. Verify country scrollable country picker or libphonenumber rules reject this prefix.',
  },
  {
    id: 'BUG-HB-004',
    module: 'Auth',
    feature: 'Login submit',
    title: 'Login request blocked by reCAPTCHA before credentials are verified',
    severity: 'Minor',
    priority: 'P1',
    status: 'Open',
    type: 'Security / UX',
    testCaseIds: 'C19',
    steps:
      '1. Go to /login\n2. Fill valid phone and password\n3. Click Log In without completing reCAPTCHA',
    expected: 'Clear message that captcha is required, or login API validates credentials after captcha.',
    actual:
      'No HamroBazar auth API call is sent; user remains on /login with no server-side invalid-credential feedback.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium)',
    evidence: 'tests/04-auth.spec.js; network trace during manual run',
    reportedBy: 'Playwright QA',
    date: '2026-06-16',
    comments: 'Expected bot protection, but blocks automated regression of C19 (invalid login feedback).',
  },
  {
    id: 'BUG-HB-005',
    module: 'Auth',
    feature: 'Invalid login feedback',
    title: 'Cannot verify error message for wrong credentials (blocked by captcha)',
    severity: 'Minor',
    priority: 'P1',
    status: 'Blocked',
    type: 'Functional',
    testCaseIds: 'C19',
    steps:
      '1. Go to /login\n2. Enter wrong phone/password\n3. Complete captcha\n4. Submit',
    expected: 'Clear error message; user stays on login page.',
    actual: 'Manual test not completed — reCAPTCHA prevents unattended verification.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome / manual',
    evidence: 'HamroBazar-Test-Cases-Detailed.csv (C19 Pending)',
    reportedBy: 'QA Team',
    date: '2026-06-16',
    comments: 'Retest manually in browser with captcha completed.',
  },
  {
    id: 'BUG-HB-006',
    module: 'Header',
    feature: 'Navigation links',
    title: 'Duplicate "Home" links on page (utility bar + logo)',
    severity: 'Minor',
    priority: 'P2',
    status: 'Fixed',
    type: 'UX / Accessibility',
    testCaseIds: 'C2, S9',
    steps:
      '1. Open homepage or /FAQ\n2. Inspect header\n3. Search DOM for links named "Home"',
    expected: 'Single unambiguous Home navigation control in the active header region.',
    actual:
      'Two links resolve to Home: utility-bar-home-link and navbar-logo-link (both href="/"). Automation cannot click by role without ambiguity.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium)',
    evidence: 'tests/05-header.spec.js; pages/HeaderPage.js uses utility-bar-home-link',
    reportedBy: 'Playwright QA',
    date: '2026-06-16',
    comments: 'Fixed in automation via getByTestId("utility-bar-home-link"). Website still has duplicate Home links for users.',
  },
  {
    id: 'BUG-HB-007',
    module: 'Header',
    feature: 'Contact link',
    title: 'Duplicate "Contact us" links visible (utility bar and footer)',
    severity: 'Minor',
    priority: 'P2',
    status: 'Fixed',
    type: 'UX / Accessibility',
    testCaseIds: 'S9, C2',
    steps:
      '1. Open homepage\n2. Scroll so footer is visible\n3. Locate Contact us links',
    expected: 'One Contact link per navigation region, or distinct labels (e.g. header vs footer).',
    actual:
      'getByRole("link", { name: /Contact us/i }) matches utility-bar-contact-link and footer-link-contact-us simultaneously.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium)',
    evidence: 'tests/05-header.spec.js; tests/06-footer.spec.js; pages use data-testid',
    reportedBy: 'Playwright QA',
    date: '2026-06-16',
    comments: 'Fixed in automation: HeaderPage uses utility-bar-contact-link; FooterPage uses footer-link-contact-us.',
  },
  {
    id: 'BUG-HB-008',
    module: 'Navigation',
    feature: 'Ad listing from homepage',
    title: 'Specific trending ad "Iphone 13 Fresh" not always present on homepage',
    severity: 'Trivial',
    priority: 'P2',
    status: 'Fixed',
    type: 'Content / Test data',
    testCaseIds: 'S6',
    steps:
      '1. Open homepage\n2. Search for listing titled "Iphone 13 Fresh"',
    expected: 'Smoke test ad remains available or test uses dynamic first ad link.',
    actual: 'Link /Iphone 13 Fresh/i not found on homepage during test run; navigation spec failed.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium)',
    evidence: 'tests/03-navigation.spec.js; tests/08-ad-detail.spec.js uses dynamic selector',
    reportedBy: 'Playwright QA',
    date: '2026-06-16',
    comments: 'Homepage listings rotate. Fixed in tests/03-navigation.spec.js using dynamic /detail/ link.',
  },
  {
    id: 'BUG-HB-009',
    module: 'Search',
    feature: 'Empty search',
    title: 'Empty search submit behavior not verified',
    severity: 'Trivial',
    priority: 'P1',
    status: 'Closed',
    type: 'Manual Verification',
    testCaseIds: 'C8',
    steps: '1. Focus search box on homepage\n2. Submit with empty query',
    expected: 'No crash; stay on page or show helpful message.',
    actual: 'Manually tested on homepage; no crash or critical issue observed on empty search submit.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Manual',
    evidence: 'HamroBazar-QA-Sheet.csv (C8 Manual)',
    reportedBy: 'QA Team',
    date: '2026-07-21',
    comments: 'Closed after manual homepage validation.',
  },
  {
    id: 'BUG-HB-010',
    module: 'Search',
    feature: 'Special characters',
    title: 'Special character and Nepali text search not verified',
    severity: 'Trivial',
    priority: 'P2',
    status: 'Closed',
    type: 'Manual Verification',
    testCaseIds: 'C9',
    steps: '1. Search @#$\n2. Search Nepali text sample\n3. Observe results',
    expected: 'No error page; application remains usable.',
    actual: 'Manually tested with special-character and Nepali query input; no critical failure observed.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Manual',
    evidence: 'HamroBazar-QA-Sheet.csv (C9 Manual)',
    reportedBy: 'QA Team',
    date: '2026-07-21',
    comments: 'Closed after manual homepage validation.',
  },
  {
    id: 'BUG-HB-011',
    module: 'Homepage',
    feature: 'All Categories',
    title: 'All Categories menu behavior not verified',
    severity: 'Trivial',
    priority: 'P1',
    status: 'Closed',
    type: 'Manual Verification',
    testCaseIds: 'C4',
    steps: '1. Open homepage\n2. Click All Categories\n3. Verify category list appears',
    expected: 'Category menu or list opens.',
    actual: 'All Categories interaction works during manual homepage test; category options are visible.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Manual',
    evidence: 'HamroBazar-Test-Cases-Detailed.csv (C4)',
    reportedBy: 'QA Team',
    date: '2026-07-21',
    comments: 'Closed after manual homepage validation.',
  },
  {
    id: 'BUG-HB-012',
    module: 'Homepage',
    feature: 'Latest uploads',
    title: 'Latest Uploads / Recommended section not verified',
    severity: 'Trivial',
    priority: 'P1',
    status: 'Closed',
    type: 'Manual Verification',
    testCaseIds: 'C5',
    steps: '1. Scroll homepage\n2. Locate Latest Uploads or Recommended section',
    expected: 'Section visible with listings.',
    actual: 'Latest Uploads / Recommended section is visible and rendering during manual homepage test.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Manual',
    evidence: 'HamroBazar-Test-Cases-Detailed.csv (C5)',
    reportedBy: 'QA Team',
    date: '2026-07-21',
    comments: 'Closed after manual homepage validation.',
  },
  {
    id: 'BUG-HB-013',
    module: 'Listing',
    feature: 'Contact seller',
    title: 'Seller contact / call option on ad detail not verified',
    severity: 'Trivial',
    priority: 'P1',
    status: 'Closed',
    type: 'Manual Verification',
    testCaseIds: 'C14',
    steps: '1. Open any ad detail page\n2. Look for contact or call button',
    expected: 'Seller contact option is visible and actionable.',
    actual: 'Manual check completed from listing to ad detail; seller contact option is visible and actionable.',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Manual',
    evidence: 'HamroBazar-Test-Cases-Detailed.csv (C14)',
    reportedBy: 'QA Team',
    date: '2026-07-21',
    comments: 'Closed after manual verification.',
  },
  {
    id: 'BUG-HB-014',
    module: 'Global',
    feature: 'Error boundary',
    title: 'Intermittent "Something went wrong — critical error occurred" page',
    severity: 'Critical',
    priority: 'P0',
    status: 'Open',
    type: 'Functional / Stability',
    testCaseIds: 'S1, C1',
    steps:
      '1. Browse https://hamrobazaar.com\n2. Navigate pages or run automated tests\n3. Observe full-page error: "Something went wrong" / "A critical error occurred. We apologize for the inconvenience."',
    expected: 'All key pages load without generic crash/error boundary screen.',
    actual:
      'Users reported generic critical error page. Main routes currently load OK in automation; error may be intermittent or tied to specific actions (login, chat, certain ads).',
    environment: 'Production — https://hamrobazaar.com',
    browser: 'Chrome (Chromium) / Safari',
    evidence: 'tests/10-critical-error.spec.js; user report; HamroBazar-Bug-Report.csv',
    reportedBy: 'Manual QA / Playwright QA',
    date: '2026-06-17',
    comments:
      'Automated guard added in tests/10-critical-error.spec.js. If error appears, note exact URL and steps; report to support@hamrobazar.com.',
  },
  {
    id: 'BUG-HB-015',
    module: 'Campaign',
    feature: 'Hamro World Cup points persistence',
    title: 'Previously earned World Cup points show as 0 for existing user',
    severity: 'Major',
    priority: 'P1',
    status: 'Open',
    type: 'Data / Regression',
    testCaseIds: 'WCP-POINTS-01',
    steps:
      '1. Login with existing Hamro World Cup participant account\n2. Open https://hamrobazaar.com/campaign\n3. Check Total Points and Points History',
    expected:
      'Previously earned points remain visible and points history/leaderboard reflect existing account progress.',
    actual:
      'Campaign page shows Total Points as 0 and no history/progress for user who reports having prior points.',
    environment: 'Production — https://hamrobazaar.com/campaign',
    browser: 'Safari (user evidence) / Chromium (verification)',
    evidence:
      '/Users/mercantile/.cursor/projects/Users-mercantile-Downloads-HamroBazar-Playwright/assets/Screenshot_2026-07-17_at_13.28.52-aec58be8-0bb6-43d1-9d34-c03d35d52259.png',
    reportedBy: 'Manual QA + User',
    date: '2026-07-21',
    comments:
      'Likely account-data/session mismatch or backend points-sync regression. Re-verify with same account identifier and points API payload.',
  },
];
